In [15]:
import numpy as np


dW1 = np.random.rand(3, 3) * 10
dW2 = np.random.rand(3, 3) * 10
grads = [dW1, dW2]
max_norm = 5.0

print(grads)

[array([[2.66582534, 2.48770567, 8.55596941],
       [2.49976491, 5.38799228, 0.08040396],
       [4.81009057, 5.40437666, 5.54659577]]), array([[5.02401701, 3.92448428, 6.15007636],
       [8.18025046, 9.53611888, 7.94459824],
       [6.50314103, 6.37048217, 1.64714855]])]


In [16]:
def clip_grads(grads, max_norm):
    total_norm = 0
    for grad in grads:
        print(grad**2)
        total_norm += np.sum(grad**2)
    total_norm = np.sqrt(total_norm)
    print(total_norm)
    
    rate = max_norm / (total_norm + 1e-6)
    if rate < 1:
        for grad in grads:
            grad *= rate #勾配が爆発しないように，次の一つ左の層に渡す前に小さくする　

In [17]:
print('before:', dW1.flatten())
clip_grads(grads, max_norm)
print('after:', dW1.flatten())


before: [2.66582534 2.48770567 8.55596941 2.49976491 5.38799228 0.08040396
 4.81009057 5.40437666 5.54659577]
[[7.10662472e+00 6.18867949e+00 7.32046125e+01]
 [6.24882459e+00 2.90304608e+01 6.46479634e-03]
 [2.31369713e+01 2.92072871e+01 3.07647246e+01]]
[[25.24074689 15.40157688 37.82343919]
 [66.91649751 90.93756337 63.11664114]
 [42.29084332 40.58304313  2.71309834]]
24.288229651845597
after: [0.54878953 0.51212163 1.76134061 0.51460416 1.1091776  0.01655204
 0.99021016 1.11255051 1.14182788]
